---
image: "docker.elastic.co/logstash/logstash"

persistence:
  enabled: true

extraInitContainers:
  - name: install-opensearch-plugin
    image: docker.elastic.co/logstash/logstash:8.5.1
    command: ["/bin/sh", "-c"]
    args:
      - bin/logstash-plugin remove logstash-integration-aws; bin/logstash-plugin install logstash-output-opensearch
    volumeMounts:
      - name: plugins
        mountPath: /usr/share/logstash/plugins

extraVolumes:
  - name: plugins
    emptyDir: {}

extraVolumeMounts:
  - name: plugins
    mountPath: /usr/share/logstash/plugins

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0

logstashPipeline:
  logstash.conf: |
    input {
      syslog {
        port => 12345
      }
    }
    output {
      opensearch {
        hosts => ["https://opensearch-cluster:9200"]       	
        ssl => true
        cacert => '/usr/share/logstash/config/opensearch-cluster-admin-cert/ca.crt'
        tls_certificate => "/usr/share/logstash/config/opensearch-cluster-admin-cert/tls.crt"
        tls_key => "/usr/share/logstash/config/opensearch-cluster-admin-cert/tls.key"
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    - name: syslog
      port: 12345
      protocol: UDP
      targetPort: 12345
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080


secretMounts: 
  - name: opensearch-cluster-admin-cert
    secretName: opensearch-cluster-admin-cert
    path: /usr/share/logstash/config/opensearch-cluster-admin-cert
