---
image: "brakhely/logstash-with-opensearch"

persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0

logstashPipeline:
  logstash.conf: |
    input {
      syslog {
        port => 12345
      }
    }
    output {
      opensearch {
        hosts => ["https://opensearch-cluster:9200"]       	
        ssl => true
        cacert => '/usr/share/logstash/config/opensearch-cluster-http-cert/ca.crt'
        tls_certificate => "/usr/share/logstash/config/opensearch-cluster-http-cert/tls.crt"
        tls_key => "/usr/share/logstash/config/opensearch-cluster-http-cert/tls.key"
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    - name: syslog
      port: 12345
      protocol: UDP
      targetPort: 12345
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080


secretMounts: 
  - name: opensearch-cluster-http-cert
    secretName: opensearch-cluster-http-cert
    path: /usr/share/logstash/config/opensearch-cluster-http-cert
