---
server:
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
  remoteWrite:
    - url: "http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push"
  persistentVolume:
    enabled: false
extraScrapeConfigs: |
  - job_name: harbor
    metrics_path: /metrics
    static_configs:
      - targets: 
        - harbor-exporter.harbor.svc.cluster.local:8001