---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: opensearch
      repoURL: https://opensearch-project.github.io/helm-charts/
      targetRevision: 2.30.1
      helm:
        valueFiles:
        - $values/opensearch-values/values.yaml
    - repoURL: https://github.com/balazsrakhely/test-monitoring-deploy.git
      targetRevision: HEAD
      path: opensearch-values
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
