apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 27.1.0
      helm:
        valueFiles:
        - $values/prometheus-values/values.yaml
    - repoURL: https://github.com/balazsrakhely/test-monitoring-deploy.git
      targetRevision: HEAD
      path: prometheus-values
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
