---
cluster:
  general:
    pluginsList: ["repository-s3"]
    additionalConfig:
      s3.client.default.endpoint: https://minio.minio-tenant:443
      s3.client.default.protocol: https
    keystore:
      - secret:
          name: s3-credentials
    snapshotRepositories:
      - name: minio-repo
        type: s3
        settings:
          bucket: opensearch-bucket
          base_path: snapshots
          path_style_access: "true"
  dashboards:
    service:
      type: NodePort
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      roles:
        - cluster_manager
        - data
