---
cluster:
  bootstrap:
    additionalConfig: &additionalConfig
      s3.client.default.endpoint: http://minio.minio-tenant.svc.cluster.local:80
      s3.client.default.access_key: minio
      s3.client.default.secret_key: minio123
      s3.client.default.protocol: http
  general:
    pluginsList: ["repository-s3"]
    additionalConfig: *additionalConfig
    snapshotRepositories:
      - name: minio-repo
        type: s3
        settings:
          bucket: opensearch-bucket
          base_path: snapshots
  dashboards:
    service:
      type: NodePort
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      roles:
        - cluster_manager
        - data
