---
cluster:
  general:
    pluginsList: ["repository-s3"]
    additionalConfig:
      s3.client.default.endpoint: http://minio.minio-tenant.svc.cluster.local:80
      s3.client.default.protocol: http
      plugins.security.ssl.http.clientauth_mode: 'OPTIONAL'
    keystore:
      - secret:
          name: s3-credentials
    snapshotRepositories:
      - name: minio-repo
        type: s3
        settings:
          bucket: opensearch-bucket
          base_path: snapshots
  dashboards:
    service:
      type: NodePort
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      roles:
        - cluster_manager
        - data
