---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: minio-tenant
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: tenant
      repoURL: https://operator.min.io
      targetRevision: 7.0.0
      helm:
        valueFiles:
        - $values/minio-tenant-values/values.yaml
    - repoURL: https://github.com/balazsrakhely/test-monitoring-deploy.git
      targetRevision: HEAD
      path: minio-tenant-values
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
