---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: opensearch-cluster
      repoURL: https://opensearch-project.github.io/opensearch-k8s-operator/
      targetRevision: 3.0.0
      helm:
        valueFiles:
        - $values/opensearch-cluster-values/values.yaml
    - repoURL: https://github.com/balazsrakhely/test-monitoring-deploy.git
      targetRevision: HEAD
      path: opensearch-cluster-values
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
