---
tenant:
  name: minio
  configuration:
    name: minio-env-configuration
  configSecret:
    name: minio-env-configuration
    accessKey: minio
    secretKey: minio123
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 1
      size: 10Gi
  buckets:
    - name: opensearch-bucket
  certificate:
    requestAutoCert: false
