---
tenant:
  name: myminio
  configuration:
    name: myminio-env-configuration
  configSecret:
    name: myminio-env-configuration
    accessKey: minio
    secretKey: minio123
  pools:
    - servers: 4
      volumesPerServer: 1
      size: 10Gi
  buckets:
    - name: opensearch-bucket
