mimir:
  structuredConfig:
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data/mimir
    server:
      http_listen_port: 8080
nginx:
  enabled: false
gateway:
  enabled: true
  enabledNonEnterprise: true
  replicaCount: 1
  ingress:
    enabled: false
