mimir:
  structuredConfig:
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /storage-data/mimir
    server:
      http_listen_port: 8080
    ruler:
      enabled: false
    compactor:
      enabled: false
nginx:
  enabled: false
gateway:
  enabled: true
  enabledNonEnterprise: true
  replicaCount: 1
  ingress:
    enabled: false
